[settings]
color_theme = "catppuccin"
status.missing_tools = "always"
install_before = "7d"
java.shorthand_vendor = "temurin"
idiomatic_version_file_enable_tools = [
    "java",
    "node",
    "npm",
    "pnpm",
    "yarn",
    "python",
]
