import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
size = 14

[scrolling]
multiplier = 1

[keyboard]
bindings = [
    { key = "q", mods = "Control|Shift", action = "Quit" },
    { key = "w", mods = "Control|Shift", action = "Quit" },
]
