import = [
    "~/.config/alacritty/theme/catppuccin-mocha.toml"
]

[window]
dimensions = { lines = 100, columns = 100 }

[scrolling]
multiplier = 1

[font]
normal = { family = "IosevkaTerm Nerd Font" }
size = 14

[cursor]
style = { shape = "Beam" }

[keyboard]
bindings = [
    { key = "q", mods = "Control|Shift", action = "Quit" },
    { key = "w", mods = "Control|Shift", action = "Quit" },
]
