vim.keymap.set({ "n", "v", "o" }, "<space>", "<nop>")
vim.keymap.set("n", "ZZ", "<nop>")
vim.keymap.set("i", "<c-j>", "<nop>")
vim.keymap.set("i", "<c-k>", "<nop>")

vim.keymap.set({ "n", "v" }, "j", "gj")
vim.keymap.set({ "n", "v" }, "<down>", "gj")
vim.keymap.set({ "n", "v" }, "k", "gk")
vim.keymap.set({ "n", "v" }, "<up>", "gk")
vim.keymap.set({ "n", "v" }, "<c-d>", "5gj")
vim.keymap.set({ "n", "v" }, "<c-u>", "5gk")
vim.keymap.set({ "n", "v" }, "<c-f>", "10gj")
vim.keymap.set({ "n", "v" }, "<c-b>", "10gk")

vim.keymap.set({ "n", "v" }, "\\", '"+')
vim.keymap.set({ "n", "v" }, "gp", '"0p=`]')
vim.keymap.set({ "n", "v" }, "gP", '"0P=`]')
vim.keymap.set({ "n", "v" }, "p", "p=`]")
vim.keymap.set({ "n", "v" }, "P", "P=`]")
vim.keymap.set("n", "<space>y", function()
	local filepath = vim.fn.expand("%:p:.")
	local lineNumber = vim.fn.line(".")
	vim.fn.setreg("+", string.format("%s:%d", filepath, lineNumber))
end, { desc = "Copy file path with line number" })
vim.keymap.set("n", "<space>Y", function()
	local filepath = vim.fn.expand("%:p")
	local lineNumber = vim.fn.line(".")
	vim.fn.setreg("+", string.format("%s:%d", filepath, lineNumber))
end, { desc = "Copy absolute file path with line number" })

vim.keymap.set("n", "<space>z", "<cmd>setlocal spell! spell?<cr>")
vim.keymap.set("n", "<space>/", "<cmd>set hlsearch! hlsearch?<cr>")

vim.keymap.set("o", "ie", "<cmd>normal! meggVG<cr>`e")
vim.keymap.set("o", "ae", "<cmd>normal! meggVG<cr>`e")

vim.keymap.set({ "n", "v" }, "H", "^")
vim.keymap.set({ "n", "v" }, "L", "$")

vim.keymap.set({ "n", "v" }, "<c-h>", "<c-w>h")
vim.keymap.set({ "n", "v" }, "<c-j>", "<c-w>j")
vim.keymap.set({ "n", "v" }, "<c-k>", "<c-w>k")
vim.keymap.set({ "n", "v" }, "<c-l>", "<c-w>l")

vim.keymap.set("t", "<esc><esc>", "<c-\\><c-n>")

vim.keymap.set({ "n", "v" }, "<f1>", "gT")
vim.keymap.set({ "n", "v" }, "<f2>", "gt")
vim.keymap.set({ "n", "v" }, "<c-w>t", "<cmd>tab split<cr>")
vim.keymap.set({ "n", "v" }, "<f3>", "<cmd>tab split<cr>")
vim.keymap.set({ "n", "v" }, "<f4>", "<c-w>T")
vim.keymap.set("i", "<f1>", "<nop>")
vim.keymap.set("i", "<f2>", "<nop>")
vim.keymap.set("i", "<f3>", "<nop>")
vim.keymap.set("i", "<f4>", "<nop>")

vim.keymap.set("c", "%%", '<c-r>=fnameescape(expand("%:h")) .. "/"<cr>')
vim.keymap.set("n", "-", "<cmd>edit %:p:h<cr>")
vim.keymap.set("n", "_", "<cmd>edit .<cr>")
vim.keymap.set("n", "<space>f", function()
	vim.ui.open(vim.fn.expand("%:h"))
end)
vim.keymap.set("n", "<space>F", function()
	vim.ui.open(".")
end)

vim.api.nvim_create_user_command("Pack", function()
	vim.pack.update()
end, {})
